#######################################################################################
# Book settings
title                       : mirdotcom  # The title of the book. Will be placed in the left navbar.
author                      : musicinformationretrieval.com contributors  # The author of the book
copyright                   : "2025"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off
  timeout: 100

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/HuwCheston/musicinformationretrieval.com  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: true

launch_buttons:
  binderhub_utl: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"